- hosts: "mysql"
  become: true
  pre_tasks:
    - name: "Install Postfix [RedHat/CentOS]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - postfix
      when: ansible_os_family == "RedHat"
    - name: "Install Python mysql and Postfix [Ubuntu]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - python-mysqldb
        - postfix
      when: ansible_distribution == "Ubuntu"
  roles:
    - role: "geerlingguy.mysql"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"

- hosts: "elasticsearch"
  become: true
  pre_tasks:
    - name: "Install Postfix [RedHat/CentOS]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - postfix
      when: ansible_os_family == "RedHat"
    - name: "Install Postfix [Ubuntu]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - postfix
      when: ansible_distribution == "Ubuntu"
  roles:
    - role: "artefactual.elasticsearch"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"

- hosts: "storage"
  become: true
  pre_tasks:
    - name: "Install MySQL Client, MySQL Client Development files and Postfix [RedHat/CentOS]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - mariadb
        - mariadb-devel
        # Postfix will be eventually a osdep
        - postfix
      when: ansible_os_family == "RedHat"
    - name: "Install MySQL Client, MySQL Client Development files, GNUPG2 and Postfix [Ubuntu]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - default-mysql-client
        - default-libmysqlclient-dev
        - gnupg2
        # Postfix will be eventually a osdep
        - postfix
      when: ansible_distribution == "Ubuntu"
  roles:
    - role: "artefactual.nginx"
    - role: "archivematica-src"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Create .ssh directory in Archivematica home folder
      file:
        path: "/var/lib/archivematica/.ssh"
        state: "directory"
        mode: "0770"
        owner: "archivematica"
        group: "archivematica"
      when: "all_configure_ssh_keys|bool"
    - name: Create/Read SSH Key for Archivematica user
      openssh_keypair:
        group: "archivematica"
        owner: "archivematica"
        path: "/var/lib/archivematica/.ssh/id_rsa"
        state: "present"
        type: "rsa"
      register: sshkey
      when: "all_configure_ssh_keys|bool"

- hosts: "dashboard"
  become: true
  pre_tasks:
    - name: "Install MySQL Client and MySQL Client Development files [RedHat/CentOS]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - mariadb
        - mariadb-devel
      when: ansible_os_family == "RedHat"
    - name: "Install MySQL Client, MySQL Client Development files and GNUPG2 [Ubuntu]"
      package:
        name: "{{item}}"
        state: present
      with_items:
        - default-mysql-client
        - default-libmysqlclient-dev
        - gnupg2
      when: ansible_distribution == "Ubuntu"
    # Install gcc-c++: https://github.com/archivematica/Issues/issues/1093
    - name: Install gcc-c++
      package:
        name: gcc-c++
        state: present
      when: ansible_os_family == "RedHat"
  roles:
    - role: "artefactual.nginx"
    - role: "artefactual.gearman"
    - role: "artefactual.clamav"
    - role: "archivematica-src"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Install authorized key from storage service
      authorized_key:
        user: "archivematica"
        state: "present"
        key: "{{hostvars[item]['sshkey']['public_key']}}"
      with_items: "{{groups['storage']}}"
      when: "all_configure_ssh_keys|bool"

- hosts: "all"
  become: true
  tasks:
    - name: Configure Postfix relayhost
      command: "/usr/sbin/postconf -e relayhost={{all_postfix_relay_host}}"
