- hosts: "mysql"
  become: true
  roles:
    - role: "geerlingguy.mysql"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"

- hosts: "elasticsearch"
  become: true
  roles:
    - role: "artefactual.elasticsearch"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"

- hosts: "storage"
  become: true
  pre_tasks:
    - name: Install mysql client
      package:
        name: mariadb
        state: present
    - name: Install mysql devel libs
      package:
        name: mariadb-devel
        state: present
  roles:
    - role: "artefactual.nginx"
    - role: "archivematica-src"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"

- hosts: "dashboard"
  become: true
  pre_tasks:
    - name: Install mysql client
      package:
        name: mariadb
        state: present
    - name: Install mysql devel libs
      package:
        name: mariadb-devel
        state: present
    # Install gcc-c++: https://github.com/archivematica/Issues/issues/1093
    - name: Install gcc-c++
      package:
        name: gcc-c++
        state: present
  roles:
    - role: "artefactual.nginx"
    - role: "artefactual.gearman"
    - role: "artefactual.clamav"
    - role: "archivematica-src"
    - role: "oasis.firewalld"
      when: ansible_os_family == "RedHat"
