# Versions
dashboard_archivematica_src_am_version: "stable/1.10.x"
storage_archivematica_src_ss_version: "stable/0.15.x"

# User to connnect to servers
archivematica_src_configure_ss_ssh_user: "root"

# MySQL Dashboard-01 Configuration
dashboard_01_archivematica_src_am_db_name: "dashboard01"
dashboard_01_archivematica_src_am_db_collation: "utf8_general_ci"
dashboard_01_archivematica_src_am_db_encoding: "utf8"
dashboard_01_archivematica_src_am_db_host_access: "10.0.200.%"
dashboard_01_archivematica_src_am_db_user: "dashboard01"
dashboard_01_archivematica_src_am_db_password: "ChangeMeDashboard01"
dashboard_01_archivematica_src_configure_am_site_url: "http://dashboard-01.example.com"
dashboard_01_archivematica_src_am_dashboard_environment:
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_SITE_URL: "{{dashboard_01_archivematica_src_configure_am_site_url}}"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER: "elasticsearch-01.example.com:9200"
  ARCHIVEMATICA_DASHBOARD_EMAIL_DEFAULT_FROM_EMAIL: "dashboard-01@example.com"
dashboard_01_archivematica_src_am_mcpclient_environment:
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER: "elasticsearch-01.example.com:9200"
  ARCHIVEMATICA_MCPCLIENT_EMAIL_DEFAULT_FROM_EMAIL: "mcpclient-01@example.com"
dashboard_01_archivematica_src_am_mcpserver_environment:
  ARCHIVEMATICA_MCPSERVER_EMAIL_DEFAULT_FROM_EMAIL: "mcpserver-01@pexample.com"

# MySQL Dashboard-02 Configuration
dashboard_02_archivematica_src_am_db_name: "dashboard02"
dashboard_02_archivematica_src_am_db_collation: "utf8_general_ci"
dashboard_02_archivematica_src_am_db_encoding: "utf8"
dashboard_02_archivematica_src_am_db_host_access: "10.0.200.%"
dashboard_02_archivematica_src_am_db_user: "dashboard02"
dashboard_02_archivematica_src_am_db_password: "ChangeMeDashboard02"
dashboard_02_archivematica_src_configure_am_site_url: "http://dashboard-02.example.com"
dashboard_02_archivematica_src_am_dashboard_environment:
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_SITE_URL: "{{dashboard_02_archivematica_src_configure_am_site_url}}"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER: "elasticsearch-02.example.com:9200"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_TIMEOUT: "60"
  ARCHIVEMATICA_DASHBOARD_EMAIL_DEFAULT_FROM_EMAIL: "dashboard-02@example.com"
dashboard_02_archivematica_src_am_mcpclient_environment:
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER: "elasticsearch-02.example.com:9200"
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHTIMEOUT: "60"
  ARCHIVEMATICA_MCPCLIENT_EMAIL_DEFAULT_FROM_EMAIL: "mcpclient-02@example.com"
dashboard_02_archivematica_src_am_mcpserver_environment:
  ARCHIVEMATICA_MCPSERVER_EMAIL_DEFAULT_FROM_EMAIL: "mcpserver-02@pexample.com"

# MySQL All settings
all_archivematica_src_am_db_host: "mysql-01.example.com"
mysql_firewalld_ports_open:
  - proto: tcp
    port: 3306

# MySQL Configuration
mysql_01_mysql_root_password: 'ChangeMeMySQLRootPassword'
mysql_01_mysql_bind_address: '0.0.0.0'

# MySQL Storge Configuration
storage_01_archivematica_src_ss_db_host: "{{all_archivematica_src_am_db_host}}"
storage_01_archivematica_src_ss_db_name: "storage01"
storage_01_archivematica_src_ss_db_collation: "utf8_general_ci"
storage_01_archivematica_src_ss_db_encoding: "utf8"
storage_01_archivematica_src_ss_db_host_access: "10.0.200.%"
storage_01_archivematica_src_ss_db_user: "storage01"
storage_01_archivematica_src_ss_db_password: "ChangeMeStorage01"
storage_01_archivematica_src_ss_environment:
  SS_DB_URL: "mysql://{{ archivematica_src_ss_db_user }}:{{ archivematica_src_ss_db_password }}@{{ archivematica_src_ss_db_host }}:3306/{{ archivematica_src_ss_db_name }}"

# Elasticsearch-01 Configuration
elasticsearch_01_elasticsearch_version: "6.5.4"
elasticsearch_01_elasticsearch_heap_size: "512m"
elasticsearch_01_elasticsearch_network_bind_host: "0.0.0.0"

# Elasticsearch-02 Configuration
elasticsearch_02_elasticsearch_version: "6.5.4"
elasticsearch_02_elasticsearch_heap_size: "512m"
elasticsearch_02_elasticsearch_network_bind_host: "0.0.0.0"

# Elasticsearch All Configuration
all_elasticsearch_max_open_files: "65535"
all_elasticsearch_java_opts: "-Duser.timezone=Europe/Amsterdam"
all_elasticsearch_index_mapper_dynamic: "true"
all_elasticsearch_memory_bootstrap_mlockall: "true"
all_elasticsearch_install_java: "true"
all_elasticsearch_thread_pools:
  - "thread_pool.write.size: 2"
  - "thread_pool.write.queue_size: 1000"
all_elasticsearch_network_http_max_content_lengtht: 1024mb
all_elasticsearch_discovery_zen_ping_multicast_enabled: "false"
all_elasticsearch_max_locked_memory: "unlimited"
elasticsearch_firewalld_ports_open:
  - proto: tcp
    port: 9200

# Dashboard/Storage Install Configuration
dashboard_archivematica_src_install_am: yes
dashboard_archivematica_src_install_ss: no
dashboard_archivematica_src_configure_dashboard: yes
dashboard_archivematica_src_configure_ss: no
dashboard_archivematica_src_install_sample_data: no
storage_archivematica_src_install_am: no
storage_archivematica_src_install_ss: yes
storage_archivematica_src_configure_dashboard: no
storage_archivematica_src_configure_ss: yes
storage_archivematica_src_install_sample_data: yes

# Archivematica Storage Configuration
storage_01_archivematica_src_configure_ss_user: "admin"
storage_01_archivematica_src_configure_ss_password: "ChangeMeSSPassword"
storage_01_archivematica_src_configure_ss_email: "archivematica-storage@example.com"
storage_01_archivematica_src_configure_ss_url: "http://storage-01.example.com:8000"
storage_firewalld_ports_open:
  - proto: tcp
    port: 8000

# Archivematica Dashboard Configuration
all_archivematica_src_configure_am_user: "admin"
all_archivematica_src_configure_am_password: "ChangeMeAMPassword"
all_archivematica_src_configure_am_email: "archivematica-dashboard@example.com"
all_archivematica_src_configure_am_org_name: "Example Organisation"
all_archivematica_src_configure_am_org_id: "EXO"
dashboard_firewalld_ports_open:
  - proto: tcp
    port: 80

# Postfix Configuration
all_postfix_relay_host: ""

# Configure SSH Keys for Storage -> Dahsboards
all_configure_ssh_keys: yes

# Extra
nodejs_install_npm_user: "{{ ansible_user_id }}"
