mysql_root_password: "{{mysql_01_mysql_root_password}}"
mysql_bind_address: "{{mysql_01_mysql_bind_address}}"
mysql_databases:
  - name: "{{storage_01_archivematica_src_ss_db_name}}"
    collation: "{{storage_01_archivematica_src_ss_db_collation}}"
    encoding: "{{storage_01_archivematica_src_ss_db_encoding}}"
  - name: "{{dashboard_01_archivematica_src_am_db_name}}"
    collation: "{{dashboard_01_archivematica_src_am_db_collation}}"
    encoding: "{{dashboard_01_archivematica_src_am_db_encoding}}"
  - name: "{{dashboard_02_archivematica_src_am_db_name}}"
    collation: "{{dashboard_02_archivematica_src_am_db_collation}}"
    encoding: "{{dashboard_02_archivematica_src_am_db_encoding}}"
mysql_users:
  - name: "{{storage_01_archivematica_src_ss_db_user}}"
    password: "{{storage_01_archivematica_src_ss_db_password}}"
    priv: "{{storage_01_archivematica_src_ss_db_name}}.*:ALL,GRANT"
    host: "{{storage_01_archivematica_src_ss_db_host_access}}"
  - name: "{{dashboard_01_archivematica_src_am_db_user}}"
    password: "{{dashboard_01_archivematica_src_am_db_password}}"
    priv: "{{dashboard_01_archivematica_src_am_db_name}}.*:ALL,GRANT"
    host: "{{dashboard_01_archivematica_src_am_db_host_access}}"
  - name: "{{dashboard_02_archivematica_src_am_db_user}}"
    password: "{{dashboard_02_archivematica_src_am_db_password}}"
    priv: "{{dashboard_02_archivematica_src_am_db_name}}.*:ALL,GRANT"
    host: "{{dashboard_02_archivematica_src_am_db_host_access}}"
firewalld_ports_open: "{{mysql_firewalld_ports_open}}"
