archivematica_src_ss_version: "{{storage_archivematica_src_ss_version}}"
archivematica_src_install_am: "{{storage_archivematica_src_install_am}}"
archivematica_src_install_ss: "{{storage_archivematica_src_install_ss}}"
archivematica_src_configure_dashboard: "{{storage_archivematica_src_configure_dashboard}}"
archivematica_src_configure_ss: "{{storage_archivematica_src_configure_ss}}"
archivematica_src_ss_environment: "{{storage_01_archivematica_src_ss_environment}}"
archivematica_src_configure_ss_user: "{{storage_01_archivematica_src_configure_ss_user}}"
archivematica_src_configure_ss_password: "{{storage_01_archivematica_src_configure_ss_password}}"
archivematica_src_configure_ss_email: "{{storage_01_archivematica_src_configure_ss_email}}"
archivematica_src_ss_db_host: "{{storage_01_archivematica_src_ss_db_host}}"
archivematica_src_ss_db_name: "{{storage_01_archivematica_src_ss_db_name}}"
archivematica_src_ss_db_user: "{{storage_01_archivematica_src_ss_db_user}}"
archivematica_src_ss_db_password: "{{storage_01_archivematica_src_ss_db_password}}"
archivematica_src_install_sample_data: "{{storage_archivematica_src_install_sample_data}}"
firewalld_ports_open: "{{storage_firewalld_ports_open}}"
